### ISSUE TITLE
dummy_onnx_run.py is missing

### ISSUE THREAD

**Issue by GaHooooo** [UT-ADL/milrem_visual_offroad_navigation#1]
Thank you very much for your work, it is really amazing. I followed the instructions in the readme file under the robot folder, but it shows that the file dummy_onnx_run.py is missing from the robot/nodes/ . Could you please provide the complete project package? Thank you.

**Comment by tambetm** [comment]
dummy_onnx_run.py was referenced only from build files (CMakeLists.txt and setup.py), it was not actually being used. Removed references to it.
